CREATE TABLE sales_activity_tasks (
  id SERIAL PRIMARY KEY NOT NULL,
  user_created INTEGER REFERENCES sales_employees(id),
  date_created TIMESTAMP,
  user_updated INTEGER REFERENCES sales_employees(id),
  date_updated TIMESTAMP,
  task_type VARCHAR(255),
  task_name VARCHAR(255),
  due_date DATE,
  description TEXT,
  priority VARCHAR(255),
  customer_name VARCHAR(255),
  customer_id VARCHAR(255),
  item_link VARCHAR(255),
  status VARCHAR(255),
  parent_task_id INTEGER REFERENCES sales_activity_tasks(id),
  sub_tasks TEXT,
  allow_completion BOOLEAN,
  stage_item_id VARCHAR(255),
  stage VARCHAR(255),
  task_id VARCHAR(255),
  sales_activity_checklists_id INTEGER REFERENCES sales_activity_checklists(id),
  isactive BOOLEAN DEFAULT FALSE,
  to_do TEXT,
  comments TEXT,
  assigned_to VARCHAR(255)
);
