CREATE TABLE sales_activity_calls (
  id SERIAL PRIMARY KEY NOT NULL,
  user_created INTEGER REFERENCES sales_employees(id),
  date_created TIMESTAMP,
  user_updated INTEGER REFERENCES sales_employees(id),
  date_updated TIMESTAMP,
  call_title VARCHAR(255),
  participants TEXT,
  call_mode VARCHAR(255),
  call_type VARCHAR(255),
  call_datetime TIMESTAMP,
  status VARCHAR(255),
  description TEXT,
  duration TIME,
  priority VARCHAR(255),
  call_agenda TEXT,
  outcome VARCHAR(255),
  call_result VARCHAR(255),
  file_url VARCHAR(255),
  stage_item_id VARCHAR(255),
  stage VARCHAR(255),
  call_id VARCHAR(255),
  sales_activity_checklists_id INTEGER REFERENCES sales_activity_checklists(id),
  isactive BOOLEAN DEFAULT FALSE,
  call_with VARCHAR(255),
  comments TEXT,
  group_with VARCHAR(255),
  assigned_to VARCHAR(255)
);

