CREATE TABLE inventory_items (
    id SERIAL PRIMARY KEY,
    user_created INTEGER,
    date_created TIMESTAMP,
    user_updated INTEGER,
    date_updated TIMESTAMP,
    quantity INTEGER,
    hsn VARCHAR(255),
    rack VARCHAR(255),
    shelf VARCHAR(255),
    "column" VARCHAR(255),
    brand VARCHAR(255),
    uom INTEGER,
    status VARCHAR(255),
    make_id int,
    model_id int,
    product_id int,
    category_id int,
    item_code VARCHAR(255),
    item_name VARCHAR(255),
    item_description VARCHAR(255),
    internal_serial_num VARCHAR(255),
    external_serial_num VARCHAR(255),
    tax_percentage VARCHAR(255),
    critical VARCHAR(255),
    parent_items_code VARCHAR(255),
    valuation_method VARCHAR(255),
    category_no VARCHAR(255),
    standard_selling_rate VARCHAR(255),
    minimum_selling_rate VARCHAR(255),
    unit_of_measures VARCHAR(255),
    group_of_item BOOLEAN,
    supplier_id VARCHAR(255),
    sales_account VARCHAR(255),
    safety_stock VARCHAR(255),
    buying_unit_of_measure VARCHAR(255),
    item_full_name VARCHAR(255),
    consumption_uom VARCHAR(255),
    buom_to_uom VARCHAR(255),
    item_for VARCHAR(255),
    cuom_to_uom VARCHAR(255),
    reorder_qty VARCHAR(255),
    purchase_account VARCHAR(255),
    isactive BOOLEAN DEFAULT FALSE,
    category_name VARCHAR(255),
    inventory_item_categories_id INT,
    parent_inventory_items_id INT,

    FOREIGN KEY (user_created) REFERENCES sales_employees(id),
    FOREIGN KEY (user_updated) REFERENCES sales_employees(id),
    FOREIGN KEY (inventory_item_categories_id) REFERENCES inventory_item_categories(id),
    FOREIGN KEY (parent_inventory_items_id) REFERENCES inventory_items(id),
    foreign key (make_id) references makes(id),
    foreign key(model_id) references models(id),
    foreign key (product_id) references products(id),
    foreign key (category_id) references categories(id)
);