CREATE TABLE public.sales_quotations (
    id SERIAL PRIMARY KEY,
    user_created INT,
    date_created TIMESTAMP,
    user_updated INT,
    date_updated TIMESTAMP,
    version VARCHAR(255),
    terms VARCHAR(255),
    valid_till TIMESTAMP,
    quotation_for VARCHAR(255),
    status VARCHAR(255),
    lost_reason VARCHAR(255),
    customer_id INT,
    quotation_type VARCHAR(255),
    quotation_date TIMESTAMP,
    order_type VARCHAR(255),
    comments VARCHAR(255),
    delivery_within VARCHAR(255),
    delivery_after VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    quotation_id VARCHAR(255) DEFAULT generate_quotation_id(),
    opportunity_id INT,
    lead_id int,
    customer_name VARCHAR(255),
    taxes VARCHAR(255),
    delivery VARCHAR(255),
    payment VARCHAR(255),
    warranty VARCHAR(255),
    freight_charge VARCHAR(255),
    is_current BOOLEAN,
    parent_sales_quotations_id INT,

    -- Foreign Keys
    CONSTRAINT fk_sales_quotation_user_created FOREIGN KEY (user_created) REFERENCES users(user_id),
    CONSTRAINT fk_sales_quotation_user_updated FOREIGN KEY (user_updated) REFERENCES users(user_id),
    CONSTRAINT fk_sales_quotation_opportunity FOREIGN KEY (opportunity_id) REFERENCES sales_opportunities(id),
    CONSTRAINT fk_sales_quotation_customer FOREIGN KEY (customer_id) REFERENCES sales_customers(id),
    CONSTRAINT fk_sales_quotation_parent FOREIGN KEY (parent_sales_quotations_id) REFERENCES sales_quotations(id),
CONSTRAINT fk_sales_quotation_lead FOREIGN KEY (lead_id) REFERENCES sales_lead(id)

);
